import type { Metadata } from "next";
import { Inter, Manrope } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Landing/footer";
import Header from "@/components/Landing/header";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:["400","500","600","700"]

});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${manrope.variable} ${inter.variable} antialiased `}>
        <ThemeProvider
         attribute= "class" 
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
          >
           <div className="flex flex-col min-h-screen">
            <Header />
            {/* The flex-1 class ensures the main area grows to fill space, 
                pushing the footer to the bottom */}
            <main className="flex-1 bg-background text-foreground">
              {children}
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}